import axios from "axios";
import { LayoutDashboard, Pencil, Plus, Save, Search, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState, type SyntheticEvent } from "react";
import { useNavigate, useParams } from "react-router-dom";
import Swal from "sweetalert2";
import api from "../../services/api";
import { resources, type FieldConfig } from "./resourceConfig";

type Row = Record<string, unknown> & { id: number };
type Option = { id: number; name: string; category?: number };

export default function ManagePage(){
  const params=useParams();const navigate=useNavigate();const resourceKey=params.resource&&resources[params.resource]?params.resource:"properties";const config=resources[resourceKey];
  const[rows,setRows]=useState<Row[]>([]);const[options,setOptions]=useState<Record<string,Option[]>>({});const[form,setForm]=useState<Record<string,unknown>>({app_id:1});const[open,setOpen]=useState(false);const[editing,setEditing]=useState<number|null>(null);const[query,setQuery]=useState("");const[busy,setBusy]=useState(false);
  const load=useCallback(()=>api.get<Row[]>(`/${config.endpoint}/`).then(r=>setRows(r.data)),[config.endpoint]);
  useEffect(()=>{void load();const endpoints=[...new Set(config.fields.map(x=>x.optionsEndpoint).filter(Boolean))] as string[];void Promise.all(endpoints.map(async endpoint=>[endpoint,(await api.get<Option[]>(`/${endpoint}/`)).data] as const)).then(entries=>setOptions(Object.fromEntries(entries)));},[config,load]);
  useEffect(()=>{if(params.id){void api.get<Row>(`/${config.endpoint}/${params.id}/`).then(r=>{setForm(r.data);setEditing(r.data.id);setOpen(true);});}},[config.endpoint,params.id]);
  const filtered=useMemo(()=>rows.filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase())),[rows,query]);
  const create=()=>{setEditing(null);setForm({app_id:1});setOpen(true)};
  const edit=(row:Row)=>{setEditing(row.id);setForm(row);setOpen(true)};
  const close=()=>{setOpen(false);setEditing(null);setForm({app_id:1});if(params.id)navigate(`/manage/${resourceKey}`)};
  const submit=async(e:SyntheticEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);try{const body=new FormData();for(const field of config.fields){const value=form[field.key];if(field.type==="file"){if(value instanceof File)body.append(field.key,value);}else if(field.type==="checkbox")body.append(field.key,value?"true":"false");else if(value!==undefined&&value!==null)body.append(field.key,String(value));}if(editing)await api.patch(`/${config.endpoint}/${editing}/`,body);else await api.post(`/${config.endpoint}/`,body);if(config.endpoint==="contact-info")window.dispatchEvent(new Event("contact-info-updated"));await Swal.fire("Saved",`${config.singular} saved successfully.`,"success");close();await load();}catch(err){const detail=axios.isAxiosError(err)?JSON.stringify(err.response?.data):"Unknown error";await Swal.fire("Unable to save",detail,"error");}finally{setBusy(false)}};
  const remove=async(row:Row)=>{const result=await Swal.fire({title:`Delete ${displayValue(row)}?`,text:"This action cannot be undone.",icon:"warning",showCancelButton:true,confirmButtonColor:"#b42318"});if(result.isConfirmed){await api.delete(`/${config.endpoint}/${row.id}/`);if(config.endpoint==="contact-info")window.dispatchEvent(new Event("contact-info-updated"));await load();}};
  return <><section className="page-banner manage-banner"><div className="container"><span className="eyebrow">Administrator workspace</span><h1>Content Management</h1><p>Manage every dynamic section of the property portal.</p></div></section><section className="section container admin-layout"><aside className="resource-nav"><h3><LayoutDashboard/>Resources</h3>{Object.entries(resources).map(([key,value])=><button key={key} className={key===resourceKey?"active":""} onClick={()=>navigate(`/manage/${key}`)}>{value.label}</button>)}</aside><div className="manager"><div className="manager-head"><div><span className="eyebrow">Manage records</span><h2>{config.label}</h2></div><button className="gold-button" onClick={create}><Plus/>Add {config.singular}</button></div><div className="table-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${config.label.toLowerCase()}`}/></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Name / title</th><th>Details</th><th>Actions</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td>{row.id}</td><td><strong>{displayValue(row)}</strong></td><td>{secondaryValue(row)}</td><td><div className="row-actions"><button className="icon-button edit" onClick={()=>edit(row)}><Pencil/></button><button className="icon-button delete" onClick={()=>void remove(row)}><Trash2/></button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-state"><p>No records found. Add the first one.</p></div>}</div></div></section>{open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="modal-head"><div><span className="eyebrow">{editing?"Update":"Create"}</span><h2>{config.singular}</h2></div><button className="icon-button" onClick={close}><X/></button></div><form className="resource-form" onSubmit={submit}>{config.fields.map(field=>{const allOptions=field.optionsEndpoint?options[field.optionsEndpoint]||[]:[];const fieldOptions=field.key==="subcategory"?allOptions.filter(option=>!form.category||String(option.category)===String(form.category)):allOptions;return <DynamicField key={field.key} field={field} value={form[field.key]} options={fieldOptions} disabled={field.key==="subcategory"&&!form.category} change={value=>{if(field.key==="category")setForm({...form,category:value,subcategory:""});else setForm({...form,[field.key]:value});}}/>})}<div className="modal-actions"><button type="button" className="clear-button" onClick={close}>Cancel</button><button className="primary-button" disabled={busy}><Save/>{busy?"Saving...":"Save changes"}</button></div></form></div></div>}</>;
}

function DynamicField({field,value,options,change,disabled=false}:{field:FieldConfig;value:unknown;options:Option[];change:(v:unknown)=>void;disabled?:boolean}){if(field.type==="textarea")return <label>{field.label}<textarea rows={5} required={field.required} value={String(value||"")} onChange={e=>change(e.target.value)}/></label>;if(field.type==="file")return <label>{field.label}<input type="file" accept="image/*" onChange={e=>change(e.target.files?.[0])}/></label>;if(field.type==="checkbox")return <label className="checkbox-label"><input type="checkbox" checked={Boolean(value)} onChange={e=>change(e.target.checked)}/>{field.label}</label>;if(field.type==="select")return <label>{field.label}<select required={field.required} disabled={disabled} value={String(value||"")} onChange={e=>change(e.target.value)}><option value="">{disabled?"Choose category first":`Select ${field.label}`}</option>{field.choices?.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;return <label>{field.label}<input type={field.type} step={field.type==="number"?"0.01":undefined} required={field.required} value={String(value??"")} onChange={e=>change(e.target.value)}/></label>}
function displayValue(row:Row){return String(row.title||row.name||row.title1||`Record ${row.id}`)}
function secondaryValue(row:Row){return String(row.location_name||row.category_name||row.country_name||row.description||"").slice(0,80)}
